### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by carol-fan** [lessthanoptimal/ExampleWebcamRPI#1]
I have finished step2(./gradlew scanqrJar),and when I run step3( java -jar scanqr.jar) ,I got this error message.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at boofcv.io.webcamcapture.UtilWebcamCapture.adjustResolution(UtilWebcamCapture.java:88)
	at boofcv.io.webcamcapture.UtilWebcamCapture.openDefault(UtilWebcamCapture.java:42)
	at WebcamScanQR.main(WebcamScanQR.java:23)

**Comment by lessthanoptimal** [comment]
Can you post information on which hardware you're using and which OS you're running on that hardware?

**Comment by carol-fan** [comment]
Sorry for uncompleted info.
Here are my device info:
1.HW----Raspberry Pi 4
2.OS----Linux
3.JDK----openjdk version "11.0.8" 2020-07-14

**Comment by lessthanoptimal** [comment]
I'll try to replicate in a few days when I have access to my RPI again thanks!
